services:
  mongo:
    image: docker.io/mongo:4.2
    ports:
      - '27888:27017'
    volumes:
      - ./mongo/:/docker-entrypoint-initdb.d/:ro
      - ../mongo-dump:/var/lib/mongo/data
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    restart: always
  
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 
    restart: always
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - 8081:8081
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=zookeeper:2181
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=host.docker.internal:29092
      - SERVER_PORT=8081
    restart: always
  
  # MICROSERVIZI EDS
  
  it-fse-srv-log-ingestion:
    image: it-fse-ms-runner                      
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-srv-log-ingestion.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 9097
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 9097:9097
    healthcheck:
      test: "curl --fail --silent localhost:9097/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s
  
  it-fse-srv-dictionary:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-srv-dictionary.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 9088
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 9088:9088
    depends_on:
      it-fse-srv-log-ingestion:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9088/status | grep UP || exit 1"
      interval: 20s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-srv-fhir:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-srv-fhir.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 9086
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 9086:9086
    depends_on:
      it-fse-srv-log-ingestion:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9086/status | grep UP || exit 1"
      interval: 20s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-srv-syntax-rules-manager:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-srv-syntax-rules-manager.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 9100
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 9100:9100
    depends_on:
      it-fse-srv-log-ingestion:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9100/status | grep UP || exit 1"
      interval: 20s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-srv-semantic-rules-manager:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-srv-semantic-rules-manager.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 9085
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 9085:9085
    depends_on:
      it-fse-srv-log-ingestion:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9085/status | grep UP || exit 1"
      interval: 20s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-datarepo-fhir-server:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-datarepo-fhir-server.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8080
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      it-fse-srv-log-ingestion:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/status | grep UP || exit 1"
      interval: 20s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-srv-query:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-srv-query.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 9091
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 9091:9091
    depends_on:
      it-fse-srv-log-ingestion:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9091/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s
  
  it-fse-datarepo-data-quality:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-datarepo-data-quality.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 9093
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 9093:9093
    depends_on:
      it-fse-srv-query:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9093/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-datarepo-processor:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-datarepo-processor.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 9089
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 9089:9089
    depends_on:
      it-fse-srv-query:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9089/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-srv-ingestion:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-srv-ingestion.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 9087
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 9087:9087
    depends_on:
      it-fse-srv-query:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9087/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  # MICROSERVIZI GATEWAY

  it-fse-gtw-rules-manager:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-rules-manager.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8011
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8011:8011
    depends_on:
      it-fse-srv-ingestion:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8011/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-gtw-eds-client:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-eds-client.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8021
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8021:8021
    depends_on:
      it-fse-srv-ingestion:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8021/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-gtw-config:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-config.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8018
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8018:8018
    depends_on:
      it-fse-srv-ingestion:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8018/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-gtw-ini-client:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-ini-client.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8020
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8020:8020
    depends_on:
      it-fse-gtw-config:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8020/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s
      
  it-fse-gtw-validator:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-validator.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8012
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8012:8012
    depends_on:
      it-fse-gtw-config:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8012/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-gtw-status-manager:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-status-manager.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8013
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8013:8013
    depends_on:
      it-fse-gtw-config:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8013/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-gtw-garbage:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-garbage.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8019
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8019:8019
    depends_on:
      it-fse-gtw-status-manager:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8019/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-gtw-status-check:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-status-check.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8017
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8017:8017
    depends_on:
      it-fse-gtw-status-manager:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8017/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s
  
  it-fse-gtw-fhir-mapping:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-fhir-mapping.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8014
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8014:8014
    depends_on:
      it-fse-gtw-rules-manager:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8014/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-gtw-fhir-mapping-engine:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-fhir-mapping-engine.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8022
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8022:8022
    depends_on:
      it-fse-gtw-rules-manager:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8022/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-gtw-publisher:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-publisher.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8016
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8016:8016
    depends_on:
      it-fse-gtw-eds-client:
        condition: service_healthy
      it-fse-gtw-status-manager:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8016/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

  it-fse-gtw-indexer:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-indexer.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8015
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8015:8015
    depends_on:
      it-fse-gtw-publisher:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8015/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s
  
  it-fse-gtw-dispatcher:
    image: it-fse-ms-runner
    build:
      context: ./../it-fse-ms-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-dispatcher.git
      BRANCH: ${CURRENT_BRANCH}
      PORT: 8010
    volumes: 
      - mvn-cache:/root/.m2
    network_mode: "bridge"
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8010:8010
    depends_on:
      it-fse-gtw-indexer:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8010/status | grep UP || exit 1"
      interval: 40s
      retries: 20
      start_period: 20s
      timeout: 10s

volumes:
  mvn-cache: